apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zoom-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shadyosama9/Zoom-Clone-K8s.git
    path: kubernetes
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true